### ISSUE TITLE
Hello Guys. Because I am so mad because these FREAKS are GATEKEEPING Universal Multiplayer, I have decided to release RiftMP on Makks' behalf. Have fun guys. https://github.com/jb0s/RiftMP

### ISSUE THREAD

**Issue by uniszn** [jb0s/RiftMP#3]
Hello Guys. Because I am so mad because these FREAKS are GATEKEEPING Universal Multiplayer, I have decided to release RiftMP on Makks' behalf. Have fun guys. https://github.com/jb0s/RiftMP

**Comment by Nintendosss** [comment]
fr

**Comment by GooferDog** [comment]
balls

**Comment by jb0s** [comment]
Yeah
